<?php

namespace App\Repository\Produit\Produit;

use Doctrine\ORM\EntityRepository;

/**
 * SouscategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SouscategorieRepository extends EntityRepository
{
public function getSelectList($id)
{
    $qb = $this->createQueryBuilder('s')
	              ->leftJoin('s.categorie', 'c')
                  ->where('c.id = :id')
                  ->setParameter('id', $id)
                  ->orderBy('s.nom','ASC');
	return $qb;
}
public function topsouscategorie($id)
{
	$query = $this->createQueryBuilder('c')
	              ->orderBy('c.nbvente','DESC')
				  ->setMaxResults($id)
                  ->getQuery();
	return $query->getResult();
}
public function myfindAll()
{
	$query = $this->createQueryBuilder('c')
	              ->orderBy('c.rang','ASC')
                  ->getQuery();
	return $query->getResult();
}
}
