parameters:
#    users_localisationuser.example.class: Users\LocalisationuserBundle\Example

services:
#    users_localisationuser.example:
#        class: %users_localisationuser.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
