<?php

namespace App\Repository\Users\Localisationuser;

use Doctrine\ORM\EntityRepository;

/**
 * DrapeauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrapeauRepository extends EntityRepository
{
}
