<?php

namespace Users\LocalisationuserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaysRepository extends EntityRepository
{
public function myfindByContinent($id,$nombreParPage,$page)
{
	if ($page < 1) {
    throw new \InvalidArgumentException('Page inexistant');
     }
	$query = $this->createQueryBuilder('p')
	              ->leftJoin('p.continent', 'c')
				  ->leftJoin('p.langues', 'l')
				  ->leftJoin('p.drapeau','d')
				  ->addSelect('d')
				  ->addSelect('l')
				  ->where('c.id = :idcon')
				  ->setParameter('idcon',$id)
				  ->orderBy('p.nom','ASC')
                  ->getQuery();
	$query->setFirstResult(($page-1) * $nombreParPage)
	      ->setMaxResults($nombreParPage);
	return new Paginator($query);
}
public function getSelectList()
{
	$qb = $this->createQueryBuilder('p')
                  ->orderBy('p.nom','ASC');
	return $qb;
}
public function myFindBy($nbresult = 10)
{
	$query = $this->createQueryBuilder('p')
	              ->leftJoin('p.drapeau','d')
				  ->addSelect('d')
				  ->where('p.siteweb LIKE  :nom')
				  ->setParameter('nom','http'.'%')
				  ->setMaxResults($nbresult)
				  ->getQuery();
	return $query->getResult();
}

public function findPaysContinent($continent,$nbresult=60)
{
	$query = $this->createQueryBuilder('p')
	              ->leftJoin('p.drapeau','d')
	              ->leftJoin('p.continent','c')
				  ->addSelect('d')
				  ->addSelect('c')
				  ->where('p.siteweb LIKE  :nom')
				  ->andWhere('c.nom LIKE  :continent')
				  ->setParameter('nom','http'.'%')
				  ->setParameter('continent','%'.$continent.'%')
				  ->orderBy('p.nom','asc')
				  ->setMaxResults($nbresult)
				  ->getQuery();
	return $query->getResult();
}
}
