parameters:
#    general_template.example.class: General\TemplateBundle\Example

services:
#    general_template.example:
#        class: %general_template.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
