produit_produit_liste_produit_souscategorie:
    path: /market/liste/produit/souscategorie/{id}
    controller: App\Controller\Produit\Produit\ProduitController:listeproduituser
    requirements:
        id: \d+
produit_produit_detail_produit_market:
    path: /market/detail/produit/{id}
    controller: App\Controller\Produit\Produit\ProduitController:detailproduit
    requirements:
        id: \d+
produit_produit_like_courant_product:
    path: /like/courant/product
    controller: App\Controller\Produit\Produit\ProduitController:likeproduct
produit_produit_ajouter_product_panier:
    path: /ajouter/product/panier
    controller: App\Controller\Produit\Produit\ProduitController:ajouterpanier
produit_produit_add_panier_produit:
    path: /add/panier/produit/{id}
    controller: App\Controller\Produit\Produit\ProduitController:addpanier
    requirements:
        id: \d+
produit_produit_reglement_commande_du_panier:
    path: /reglement/commande/dupanier/{id}
    controller: App\Controller\Produit\Produit\ProduitController:reglementcommande
    requirements:
        id: \d+
produit_produit_editer_courant_commande:
    path: /edit/courant/commande
    controller: App\Controller\Produit\Produit\ProduitController:editcommande
    requirements:
        id: \d+
produit_produit_elever_produit_commande:
    path: /enleve/produit/commande/{id}
    controller: App\Controller\Produit\Produit\ProduitController:eleveproduit
    requirements:
        id: \d+
produit_produit_recherche_new_produit:
    path: /recherche/new/produit
    controller: App\Controller\Produit\Produit\ProduitController:rechercheproduit
produit_produit_modifier_lieu_livraison:
    path: /modifier/lieu/livraison/panier/{id}
    controller: App\Controller\Produit\Produit\PanierController:modifierlieulivraison
    requirements:
        id: \d+
produit_produit_payement_dupanier_utilisateur:
    path: /payement/dupanier/utilisateur/{id}/{montant}
    controller: App\Controller\Produit\Produit\PanierController:payementpanier
    defaults:
        montant: 0
    requirements:
        id: \d+
produit_produit_ajout_nom_domaine_panier:
    path: /ajouter/domaine/panier/{domaine}
    controller: App\Controller\Produit\Produit\PanierController:ajoutdomaine
    defaults:
        domaine: ''
produit_produit_application_references:
    path: /applications
    controller: App\Controller\Produit\Produit\ProduitController:nosreferences
produit_produit_application_references_slache:
    path: /applications/
    controller: App\Controller\Produit\Produit\ProduitController:nosreferences
produit_produit_service_struct:
    path: /services
    controller: App\Controller\Produit\Produit\ProduitController:servicesstruct
produit_produit_service_struct_slache:
    path: /services/
    controller: App\Controller\Produit\Produit\ProduitController:servicesstruct
produit_produit_about_us:
    path: /about/us
    controller: App\Controller\Produit\Produit\ProduitController:aboutuser
produit_produit_about_us_slache:
    path: /about/us/
    controller: App\Controller\Produit\Produit\ProduitController:aboutuser