produit_service_contact_us:
    path: /nous/contacter
    controller: App\Controller\Produit\Service\MessageController:contactus
produit_service_contact_us_slache:
    path: /nous/contacter/
    controller: App\Controller\Produit\Service\MessageController:contactus
produit_service_chargement_statatistique_annee:
    path: /chargement/statatistique/annee/{position}/{anneeid}
    controller: App\Controller\Produit\Service\ServiceController:applicationstat
    defaults:
        position: 0
        anneeid: 0
    requirements:
        position: \d+
        anneeid: \d+
produit_service_callback_homepage:
    path: /callback/homepage/afh
    controller: App\Controller\Produit\Service\ServiceController:callbackhomepage
