produit_service_contact_us:
    path: /nous/contacter
    controller: App\Controller\Produit\Service\MessageController:contactus
produit_service_contact_us_slache:
    path: /nous/contacter
    controller: App\Controller\Produit\Service\MessageController:contactus
produit_service_chargement_statatistique_annee:
    path: /chargement/statatistique/annee/{position}/{anneeid}
    controller: App\Controller\Produit\Service\ServiceController:applicationstat
    defaults:
        position: 0
        anneeid: 0
    requirements:
        position: \d+
        anneeid: \d+
produit_service_callback_homepage:
    path: /callback/homepage/afh
    controller: App\Controller\Produit\Service\ServiceController:callbackhomepage
produit_service_articles_support:
    path: /articles/support/{position}/{page}/{idType}
    controller: App\Controller\Produit\Service\ServiceController:articlessupport
    defaults:
        position: 'about'
        page: 1
        idType: 0
    requirements:
        page: \d+
        idType: \d+
produit_service_open_quiz_response:
    path: /open/quiz/{page}
    controller: App\Controller\Produit\Service\ServiceController:openQuiz
    defaults:
        page: 1
produit_service_commentaire_article:
    path: /commentaire/article/{id}
    controller: App\Controller\Produit\Service\ServiceController:commentaireArticle
    requirements:
        id: \d+
produit_service_branding_shop:
    path: /branding/shop/{page}
    controller: App\Controller\Produit\Service\ServiceController:brandingShop
    defaults:
        page: 1
    requirements:
        page: \d+
produit_service_contacts:
    path: /contacts
    controller: App\Controller\Produit\Service\ServiceController:contacts