<?php

namespace Produit\ServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository
{
public function myfindAll()
{
	$query = $this->createQueryBuilder('s')
	              ->orderBy('s.date','ASC')
                  ->getQuery();
	return $query->getResult();
}
public function getSelectIndicateur()
{
    $qb = $this->createQueryBuilder('s')
                  ->where('s.type = 1')
                  ->orderBy('s.nom','ASC');
	return $qb;
}
public function getSelectAnnee()
{
    $qb = $this->createQueryBuilder('s')
                  ->where('s.type = 0')
                  ->orderBy('s.nom','ASC');
	return $qb;
}
}
