<?php

namespace App\Repository\Users\User;

use Doctrine\ORM\EntityRepository;

/**
 * InvestissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvestissementRepository extends EntityRepository
{
public function myFindAll(){
	$query = $this->createQueryBuilder('i')
				  ->orderBy('i.date','desc')
				  ->getQuery();
	return $query->getResult();
}
}
