<?php

namespace App\Repository\Users\User;

use Doctrine\ORM\EntityRepository;

use App\Entity\Users\User\User;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;



/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends ServiceEntityRepository
{
public function __construct(ManagerRegistry $registry)
{
	parent::__construct($registry, User::class);
}

public function findTeam($nbresult = 20){
	$query = $this->createQueryBuilder('u')
				  ->where('u.roles LIKE  :nom or u.roles LIKE  :nom2')
				  ->setParameter('nom','%ROLE_ADMIN%')
				  ->setParameter('nom2','%ROLE_TEAM%')
				  ->orderBy('u.nom','asc')
				  ->setMaxResults($nbresult)
				  ->getQuery();
	return $query->getResult();
}
}
