<?php
namespace App\Repository\Produit\Service;


use Doctrine\ORM\EntityRepository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use App\Entity\Produit\Service\Imgevenement;

/**
 * ImgevenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
 class ImgevenementRepository extends ServiceEntityRepository
 {
	 public function __construct(ManagerRegistry $registry)
	 {
		 parent::__construct($registry, Imgevenement::class);
	 }

}
