<?php

namespace Produit\ServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
public function myfindAll()
{
	$query = $this->createQueryBuilder('m')
	              ->orderBy('m.date','DESC')
                  ->getQuery();
	return $query->getResult();
}
public function myfindmessvalide($id)
{
	$query = $this->createQueryBuilder('m')
				  ->leftJoin('m.user','u')
				  ->where('m.valide = 1')
				  ->orWhere('u.id = :id')
				  ->setParameter('id',$id)
	              ->orderBy('m.date','DESC')
                  ->getQuery();
	return $query->getResult();
}
}
