<?php

namespace App\Repository\Produit\Service;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository
{
public function myfindAll()
{
	$query = $this->createQueryBuilder('s')
	              ->orderBy('s.date','ASC')
                  ->getQuery();
	return $query->getResult();
}

public function getSelectIndicateur()
{
    $qb = $this->createQueryBuilder('s')
               ->where('s.type = 1')
               ->orderBy('s.nom','ASC');
	return $qb;
}

public function getSelectAnnee()
{
    $qb = $this->createQueryBuilder('s')
               ->where('s.type = 0')
               ->orderBy('s.nom','ASC');
	return $qb;
}

public function findAllArticle($id, $page, $nombreParPage)
{
	if($page < 1){
		throw new \InvalidArgumentException('Page inexistant');
	}
	$query = $this->createQueryBuilder('s')
				  ->leftJoin('s.typearticle','t')
				  ->addSelect('t')
				  ->where('t.id =:id')
				  ->setParameter('id',$id)
	              ->orderBy('s.rang','ASC')
                  ->getQuery();
	$query->setFirstResult(($page-1) * $nombreParPage)
		  ->setMaxResults($nombreParPage);
	return new Paginator($query);
}

public function myFindAllPagineType($type, $page, $nombreParPage)
{
	if ($page < 1){
	throw new \InvalidArgumentException('Page inexistant');
	}
	$query = $this->createQueryBuilder('s')
	              ->leftJoin('s.typearticle','t')
				  ->addSelect('t')
	              ->where('s.type LIKE :n')
				  ->setParameter('n','%'.$type.'%')
	              ->orderBy('s.rang','ASC')
                  ->getQuery();
	$query->setFirstResult(($page-1) * $nombreParPage)
		  ->setMaxResults($nombreParPage);
	return new Paginator($query);
}

public function myFindByTypearticlePagine($id, $type, $page, $nombreParPage)
{
	if ($page < 1){
	throw new \InvalidArgumentException('Page inexistant');
	}
	$query = $this->createQueryBuilder('s')
	              ->leftJoin('s.typearticle','t')
				  ->addSelect('t')
	              ->where('s.type LIKE :n AND t.id = :id')
				  ->setParameter('n','%'.$type.'%')
				  ->setParameter('id',$id)
	              ->orderBy('s.rang','ASC')
                  ->getQuery();
	$query->setFirstResult(($page-1) * $nombreParPage)
		  ->setMaxResults($nombreParPage);
	return new Paginator($query);
}
}
