<?php
namespace App\Repository\Produit\Service;


use Doctrine\ORM\EntityRepository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use App\Entity\Produit\Service\Typearticle;

/**
 * TypearticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
 class TypearticleRepository extends ServiceEntityRepository
 {
	 public function __construct(ManagerRegistry $registry)
	 {
		 parent::__construct($registry, Typearticle::class);
	 }

public function myFindScatType($id, $type)
{
	$query = $this->createQueryBuilder('t')
	              ->leftJoin('t.services','s')
	              ->leftJoin('s.souscategorie','sc')
				  ->addSelect('s')
				  ->addSelect('sc')
	              ->where('t.position LIKE :n AND sc.id =:id')
				  ->setParameter('n','%'.$type.'%')
				  ->setParameter('id',$id)
	              ->orderBy('t.rang','ASC')
                  ->getQuery();
	return $query->getResult();
}

public function myFindOneType($type='')
{
	$query = $this->createQueryBuilder('t')
	              ->leftJoin('t.services','s')
				  ->addSelect('s')
	              ->where('t.position LIKE :n')
				  ->setParameter('n','%'.$type.'%')
	              ->orderBy('t.rang','ASC')
	              ->setMaxresults(1)
                  ->getQuery();
	return $query->getOneORNullResult();
}
}
