<?php

namespace Produit\ProduitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
public function myFindAll()
{
	$query = $this->createQueryBuilder('c')
	              ->leftJoin('c.souscategories','s')
				  ->addSelect('s')
	              ->orderBy('c.date','ASC')
                  ->getQuery();
	return $query->getResult();
}
}
